name: Build Conan dependencies
description: "Install Conan dependencies, optionally forcing a rebuild of all dependencies."

# Note that actions do not support 'type' and all inputs are strings, see
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#inputs.
inputs:
  verbosity:
    description: "The build verbosity."
    required: false
    default: "verbose"
  build_dir:
    description: "The directory where to build."
    required: true
  build_type:
    description: 'The build type to use ("Debug", "Release").'
    required: true
  force_build:
    description: 'Force building of all dependencies ("true", "false").'
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Conan dependencies
      shell: bash
      env:
        BUILD_DIR: ${{ inputs.build_dir }}
        BUILD_OPTION: ${{ inputs.force_build == 'true' && '*' || 'missing' }}
        BUILD_TYPE: ${{ inputs.build_type }}
        VERBOSITY: ${{ inputs.verbosity }}
      run: |
        echo 'Installing dependencies.'
        mkdir -p "${BUILD_DIR}"
        cd "${BUILD_DIR}"
        conan install \
          --output-folder . \
          --build="${BUILD_OPTION}" \
          --options:host='&:tests=True' \
          --options:host='&:xrpld=True' \
          --settings:all build_type="${BUILD_TYPE}" \
          --conf:all tools.build:verbosity="${VERBOSITY}" \
          --conf:all tools.compilation:verbosity="${VERBOSITY}" \
          ..
